# syntax=docker/dockerfile:1


FROM python:3.8-slim-buster

WORKDIR /app

COPY ./requirements.txt requirements.txt

RUN pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com



