version: '3'

services:
  api:
    image: {{cookiecutter.project_name}}
    build:
      context: .
    restart: always
    command: bash -c "flask db migrate && flask db upgrade && gunicorn run:app"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./migrations:/app/migrations
    ports:
      - 15000:5000

  redis:
      image: redis:alpine
      restart: always
      environment:
        TZ: 'GMT+8'
      hostname: redis

  celery-worker:
    image: {{cookiecutter.project_name}}
    build:
      context: .
    restart: always
    command: celery -A runcelery.celery worker
    depends_on:
      - redis
      - api
    links:
      - redis

  celery-beat:
    image: {{cookiecutter.project_name}}
    build:
      context: .
    restart: always
    command: celery -A runcelery.celery beat
    depends_on:
      - redis
      - api
    links:
      - redis